# Generated by Django 4.2.7 on 2025-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birthdays", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="Дата рождения",
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
